mysql:
  dsn: mysql://root:root123456@127.0.0.1:3306/aestival-auth?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addrs:
    - redis://:aestival@127.0.0.1:6379
    - redis://:aestival@127.0.0.1:6380
    - redis://:aestival@127.0.0.1:6381
    - redis://:aestival@127.0.0.1:6382
    - redis://:aestival@127.0.0.1:6383
    - redis://:aestival@127.0.0.1:6384